twig:
  globals:
    on_invoice_fee_percentage: '%coolminds_pay_by_invoice.fee_percentage%'
    on_invoice_payment_code: '%coolminds_pay_by_invoice.payment_code%'
    on_invoice_display_in_description: '%coolminds_pay_by_invoice.display_in_description%'
