parameters:
  coolminds_pay_by_invoice.fee_percentage: 2.5
  coolminds_pay_by_invoice.payment_code: 'on_invoice'
  coolminds_pay_by_invoice.display_in_description: true

services:
  Coolminds\PayByInvoice\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Resources,Tests}'

  Coolminds\PayByInvoice\Processors\OnInvoiceFeeProcessor:
    arguments:
      $onInvoicePaymentCode: '%coolminds_pay_by_invoice.payment_code%'
      $feePercentage: '%coolminds_pay_by_invoice.fee_percentage%'
      $adjustmentFactory: '@sylius.factory.adjustment'
      $translator: '@translator'
    tags:
      - { name: sylius.order_processor, priority: 10 }

  Coolminds\PayByInvoice\Form\Extension\PaymentMethodChoiceTypeExtension:
    arguments:
      $onInvoiceFeePercentage: '%coolminds_pay_by_invoice.fee_percentage%'
      $onInvoiceDisplayInDescription: '%coolminds_pay_by_invoice.display_in_description%'
      $onInvoiceGroupCode: '%coolminds_pay_by_invoice.payment_code%'
    tags:
      - { name: form.type_extension }
